version: "3.8"

services:
  db:
    image: nouchka/sqlite3:latest # Utilise l'image Docker de SQLite3 à partir du Docker Hub
    volumes:
      - ./data/db:/root/db # Monte le répertoire local ./data/db dans /root/db du conteneur
    environment:
      - DJANGO_DATABASE_NAME=oc-lettings-site # Spécifie le nom de la base de données SQLite3
  web:
    command: python manage.py runserver 0.0.0.0:8000 # Commande à exécuter pour lancer le serveur Django
    ports:
      - "8000:8000" # Exposer le port 8000 du conteneur sur le port 8000 de l'hôte
    depends_on:
      - db # Assure que le service 'db' est démarré avant le service 'web'
