version: "3.8"

services:
  web:
    command:
      > # Commande à exécuter pour lancer la migration et le serveur Django
      sh -c "python manage.py migrate &&                        
             python manage.py runserver 0:80"
    ports:
      - "80:80" # Exposer le port 80 du conteneur sur le port 8000 de l'hôte
    depends_on:
      - db # Assure que le service 'db' est démarré avant le service 'web'
