# Generated by Django 3.0 on 2024-06-10 16:00

import os
from django.db import migrations
from tools.tools import read_sql

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            read_sql('lettings', 'insert_data_from_oc.sql'),
            reverse_sql=read_sql('lettings', 'reverse_insert_data_from_oc.sql'),
        ),
    ]
