# Generated by Django 3.0 on 2024-06-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_delete_address_letting'),
        ('profiles', '0002_data_from_oc_profile')
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
