name: Django CI and Delivery

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Creates and sets environment variable
      id: dot_env_creation
      run: |
        echo "DSN=${{ secrets.SENTRY_DSN }}" > .env
        echo "APP_SECRET_KEY=${{ secrets.APP_SECRET_KEY }}" >> .env

    - name: Run linting
      run: |
        flake8
      if: ${{ steps.dot_env_creation.outcome }} == "success"
      
    - name: Run Tests
      run: |
        python manage.py test
      if: ${{ steps.dot_env_creation.outcome }} == "success"

    - name: Ensures test coverage is above 80%
      id: coverage_test
      run: |
        pytest --cov-fail-under=80
      if: ${{ steps.dot_env_creation.outcome }} == "success"
   
